version: '3'
services:
  web:
    #image: web:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /node_modules
      - .:/app
    command: ['npm', 'run', 'test']
